services:
  # MinIO Server
  minio:
    image: minio/minio:latest
    container_name: api-minio-1
    ports:
      - "9000:9000" # منفذ API
      - "9001:9001" # منفذ لوحة التحكم (Console)
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - minio_data:/data
    # السطر التالي هو الذي يمنع الحاوية من التوقف (Exited 0)
    command: server /data --console-address ":9001"
    networks:
      - app-network
    healthcheck:
      # تم تقليل الوقت (interval) لكي يعمل minio-client بسرعة أكبر
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MinIO Client - لإنشاء الـ Buckets تلقائياً
  minio-client:
    image: minio/mc:latest
    container_name: minio-client
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 admin 12345678;
      /usr/bin/mc mb myminio/products --ignore-existing;
      /usr/bin/mc mb myminio/categories --ignore-existing;
      /usr/bin/mc mb myminio/uploads --ignore-existing;
      /usr/bin/mc anonymous set download myminio/products;
      /usr/bin/mc anonymous set download myminio/categories;
      /usr/bin/mc anonymous set download myminio/uploads;
      exit 0;
      "
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  minio_data: