import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateWalletAndUUID1774005493230 implements MigrationInterface {
    name = 'UpdateWalletAndUUID1774005493230'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "wallets" ("id" SERIAL NOT NULL, "balance" numeric(10,2) NOT NULL DEFAULT '0', "userId" uuid NOT NULL, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_2ecdb33f23e9a6fc392025c0b9" UNIQUE ("userId"), CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "url" character varying NOT NULL, "key" character varying NOT NULL, "originalName" character varying, "mimeType" character varying, "size" integer, "folder" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "PK_1fe148074c6a1a91b63cb9ee3c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "imageUrl" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "isActive" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', "slug" character varying, "mpath" character varying DEFAULT '', "parentId" uuid, "storeId" uuid NOT NULL, CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a8a585f8f8acb7dba7112b9ee6" ON "categories" ("storeId", "parentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b46b2ebf13699bb37073964de2" ON "categories" ("storeId", "isActive") `);
        await queryRunner.query(`CREATE TABLE "niches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name_en" character varying NOT NULL, "name_ar" character varying NOT NULL, "name_fr" character varying NOT NULL, "slug" character varying NOT NULL, "icon" character varying NOT NULL, CONSTRAINT "PK_d0215f97e70a9565e6db34d341f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "store_designs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "primaryColor" character varying NOT NULL DEFAULT '#8b5cf6', "secondaryColor" character varying NOT NULL DEFAULT '#ec4899', "logoUrl" character varying, "storeId" uuid, CONSTRAINT "REL_017647ff1af091772e3bdf80ba" UNIQUE ("storeId"), CONSTRAINT "PK_fbfcd076c05f65c4760a3bffa23" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "store_topbars" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "enabled" boolean NOT NULL DEFAULT true, "text" character varying, "color" character varying NOT NULL DEFAULT '#6366f1', "storeId" uuid, CONSTRAINT "REL_6549c1d9ad39cd06be3d213e3b" UNIQUE ("storeId"), CONSTRAINT "PK_2f542a285ff5a027668284de2f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "store_contacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying, "phone" character varying, "wilaya" character varying, "storeId" uuid, CONSTRAINT "REL_1627fed74b48fa87174a0e6662" UNIQUE ("storeId"), CONSTRAINT "PK_236fd92cefc3b2353125d652f08" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "store_hero_sections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "imageUrl" character varying, "title" character varying, "subtitle" character varying, "storeId" uuid, CONSTRAINT "REL_d2d33adeaf7b8f987e4d8e274f" UNIQUE ("storeId"), CONSTRAINT "PK_b89aadba2b6067730fd6515113d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "store_pixels_type_enum" AS ENUM('facebook', 'tiktok', 'google', 'snapchat')`);
        await queryRunner.query(`CREATE TABLE "store_pixels" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "store_pixels_type_enum" NOT NULL DEFAULT 'facebook', "pixelId" character varying(255) NOT NULL, "accessToken" character varying(255), "isActive" boolean NOT NULL DEFAULT true, "events" json, "customData" json, "storeId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_71c1436953bdacca4b5dd5f51ec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "theme_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, CONSTRAINT "UQ_a3d05fc0c8ea908be1456d952d2" UNIQUE ("name"), CONSTRAINT "PK_8b092019a915d500ee58441bec8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "theme" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name_en" character varying NOT NULL, "name_ar" character varying NOT NULL, "name_fr" character varying NOT NULL, "slug" character varying NOT NULL, "price" double precision NOT NULL DEFAULT '0', "desc_en" text NOT NULL, "desc_ar" text NOT NULL, "desc_fr" text NOT NULL, "imageUrl" character varying NOT NULL, "tag" json, "typeId" uuid NOT NULL, "isActive" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_36551e08e2fc4b5b68b48b4ef97" UNIQUE ("slug"), CONSTRAINT "PK_c1934d0b4403bf10c1ab0c18166" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "theme_user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "themeId" uuid NOT NULL, "userId" character varying NOT NULL, CONSTRAINT "UQ_87a2f1feb2e0cc373989d45cd17" UNIQUE ("themeId", "userId"), CONSTRAINT "PK_8fa0b204a23059c031e60f6a3a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "subdomain" character varying NOT NULL, "currency" character varying NOT NULL DEFAULT 'DZD', "language" character varying NOT NULL DEFAULT 'ar', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "themeUserId" uuid, "userId" uuid, "nicheId" uuid, CONSTRAINT "UQ_f9d41ef03498f27cf2dda8e87d9" UNIQUE ("subdomain"), CONSTRAINT "PK_7aa6e7d71fa7acdd7ca43d7c9cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_variants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "value" character varying NOT NULL, "attributeId" uuid, "ordersId" uuid, CONSTRAINT "PK_281e3f2c55652d6a22c0aa59fd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_attributes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" character varying NOT NULL, "displayMode" character varying, "productId" uuid, CONSTRAINT "PK_4fa18fc5c893cb9894fc40ca921" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "variant_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" json NOT NULL, "price" double precision NOT NULL DEFAULT '0', "stock" integer NOT NULL DEFAULT '0', "autoGenerate" boolean NOT NULL DEFAULT false, "productId" uuid, CONSTRAINT "PK_b2b72a94376845f82375c2bf390" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_offers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "quantity" integer NOT NULL, "price" double precision NOT NULL, "productId" uuid, CONSTRAINT "PK_5acf99c4c02b2a7129c80278971" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product-images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "imageUrl" character varying NOT NULL, "productId" uuid, CONSTRAINT "PK_d8a34eb9070e1dc64180c287deb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "desc" text, "price" numeric(10,2) NOT NULL, "priceOriginal" numeric(10,2), "productImage" character varying, "isActive" boolean NOT NULL DEFAULT true, "stock" integer NOT NULL DEFAULT '0', "sku" character varying, "slug" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "storeId" uuid NOT NULL, "categoryId" uuid, CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bb4c06bfc223160d712f7ea457" ON "products" ("storeId", "isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_56b0fbad8cf5578cb7536e9839" ON "products" ("storeId", "categoryId") `);
        await queryRunner.query(`CREATE TABLE "shows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid, "storeId" uuid, "lpId" uuid, "visitorId" character varying NOT NULL, "dayDate" date NOT NULL DEFAULT ('now'::text)::date, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9c8e1ce9f934165c07f0fbea1fb" UNIQUE ("visitorId", "productId", "storeId", "dayDate"), CONSTRAINT "PK_db2b12161dbc5081c4f50025669" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "landing-pages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "domain" character varying NOT NULL, "urlImage" character varying NOT NULL, "productId" uuid NOT NULL, "platform" character varying NOT NULL DEFAULT 'md store', "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_3715b0116b5973d06be3d726e2d" UNIQUE ("domain"), CONSTRAINT "PK_02e571dc3925cc315b26006881c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "orders_typeship_enum" AS ENUM('home', 'office')`);
        await queryRunner.query(`CREATE TYPE "orders_status_enum" AS ENUM('pending', 'appl1', 'appl2', 'appl3', 'confirmed', 'shipping', 'cancelled', 'returned', 'delivered', 'postponed')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "storeId" uuid NOT NULL, "priceShip" numeric(10,2) NOT NULL, "priceLoss" numeric(10,2) NOT NULL, "totalPrice" numeric(10,2) NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "platform" character varying, "typeShip" "orders_typeship_enum" NOT NULL DEFAULT 'home', "unityPrice" numeric(10,2), "variantDetailId" uuid, "offerId" uuid, "status" "orders_status_enum" NOT NULL DEFAULT 'pending', "isUploadedShipping" boolean NOT NULL DEFAULT false, "customerId" character varying NOT NULL, "customerName" character varying NOT NULL, "customerPhone" character varying NOT NULL, "customerWilayaId" integer NOT NULL, "customerCommuneId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "confirmedAt" TIMESTAMP, "shippingAt" TIMESTAMP, "deliveredAt" TIMESTAMP, "lpId" uuid, "postponedUntil" TIMESTAMP, CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "communes" ("id" integer NOT NULL, "name" character varying NOT NULL, "ar_name" character varying NOT NULL, "post_code" character varying, "wilayaId" integer NOT NULL, CONSTRAINT "PK_53a9285bb669dd2298c4de525bb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "wilayas" ("id" integer NOT NULL, "name" character varying NOT NULL, "ar_name" character varying NOT NULL, CONSTRAINT "PK_fee33960793c27e45b3162eb0d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shippings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "wilayaId" integer NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "priceHome" numeric(10,2) NOT NULL DEFAULT '0', "priceOffice" numeric(10,2) NOT NULL DEFAULT '0', "priceReturn" numeric(10,2) NOT NULL DEFAULT '0', CONSTRAINT "UQ_7109b58f70387e75e0c475588cc" UNIQUE ("userId", "wilayaId"), CONSTRAINT "PK_665fb613135782a598a2b47e5b2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "transactions_action_enum" AS ENUM('payment', 'deposit')`);
        await queryRunner.query(`CREATE TYPE "transactions_type_enum" AS ENUM('plan_subscription', 'plan_upgrade', 'store_fee', 'refund', 'sell_theme', 'top_up')`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" SERIAL NOT NULL, "action" "transactions_action_enum" NOT NULL, "type" "transactions_type_enum" NOT NULL, "amount" numeric(10,2) NOT NULL, "typeId" integer, "userId" uuid NOT NULL, "providerTransactionId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_91e31a934485712dd3e06c135bd" UNIQUE ("providerTransactionId"), CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "plan_features" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "storeNumber" integer NOT NULL DEFAULT '0', "productNumber" integer NOT NULL DEFAULT '0', "landingPageNumber" integer NOT NULL DEFAULT '0', "isNtfy" boolean NOT NULL DEFAULT false, "pixelTiktokNumber" integer NOT NULL DEFAULT '0', "pixelFacebookNumber" integer NOT NULL DEFAULT '0', "commission" numeric(5,2) NOT NULL DEFAULT '0', "theme" json, CONSTRAINT "PK_eb2b32d1d93a8b2e96e122e3a77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "monthlyPrice" numeric(10,2) NOT NULL DEFAULT '0', "yearlyPrice" numeric(10,2) NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'DZD', "stripePriceId" character varying, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "featuresId" uuid, CONSTRAINT "REL_f998a690a409e6e90f956c7030" UNIQUE ("featuresId"), CONSTRAINT "PK_3720521a81c7c24fe9b7202ba61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "subscriptions_status_enum" AS ENUM('active', 'canceled', 'expired', 'past_due', 'trailing_period')`);
        await queryRunner.query(`CREATE TYPE "subscriptions_interval_enum" AS ENUM('month', 'year')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "planId" uuid NOT NULL, "status" "subscriptions_status_enum" NOT NULL DEFAULT 'active', "interval" "subscriptions_interval_enum" NOT NULL DEFAULT 'month', "stripeSubscriptionId" character varying, "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP NOT NULL, "cancelAtPeriodEnd" boolean NOT NULL DEFAULT false, "autoRenew" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "users_provider_enum" AS ENUM('CREDENTIALS', 'GOOGLE', 'CREDENTIALS_GOOGLE')`);
        await queryRunner.query(`CREATE TYPE "users_role_enum" AS ENUM('NORMAL_USER', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying, "provider" "users_provider_enum" NOT NULL DEFAULT 'CREDENTIALS', "role" "users_role_enum" NOT NULL DEFAULT 'NORMAL_USER', "topic" character varying, "isNtfy" boolean NOT NULL DEFAULT true, "password" character varying, "image" character varying, "otp" integer, "isVerified" boolean NOT NULL DEFAULT false, "otpExpires" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_d27fbf27590253b8f008cd5645a" UNIQUE ("topic"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "store_shipping_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "store_id" uuid NOT NULL, "provider_name" character varying(64) NOT NULL, "credentials" text NOT NULL, "is_verified" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_53ba2de9da70861cda5fcba3b7" UNIQUE ("store_id"), CONSTRAINT "PK_0863a8893b86c6b40bd89a8c208" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "admin" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying NOT NULL, "email" character varying NOT NULL, "key" integer NOT NULL, "password" character varying NOT NULL, CONSTRAINT "PK_e032310bcef831fb83101899b10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_2ecdb33f23e9a6fc392025c0b97" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "images" ADD CONSTRAINT "FK_96514329909c945f10974aff5f8" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa" FOREIGN KEY ("parentId") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_fa6ba3528de12e174b163c09fdd" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_designs" ADD CONSTRAINT "FK_017647ff1af091772e3bdf80ba2" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_topbars" ADD CONSTRAINT "FK_6549c1d9ad39cd06be3d213e3b5" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_contacts" ADD CONSTRAINT "FK_1627fed74b48fa87174a0e66620" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_hero_sections" ADD CONSTRAINT "FK_d2d33adeaf7b8f987e4d8e274fb" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_pixels" ADD CONSTRAINT "FK_d672c71dc8dd7bb3670942830e3" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "theme" ADD CONSTRAINT "FK_9eb2f43ba51035528ddb77e8982" FOREIGN KEY ("typeId") REFERENCES "theme_type"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "theme_user" ADD CONSTRAINT "FK_93dccfcad09b5fb21e1e96e609e" FOREIGN KEY ("themeId") REFERENCES "theme"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stores" ADD CONSTRAINT "FK_f36d697e265ed99b80cae6984c9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stores" ADD CONSTRAINT "FK_a3f1c17291011aa7bc7620df482" FOREIGN KEY ("nicheId") REFERENCES "niches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stores" ADD CONSTRAINT "FK_ba690aca3652a749546e8df22dc" FOREIGN KEY ("themeUserId") REFERENCES "theme_user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_f31b2790936aab19a62e4c0828a" FOREIGN KEY ("attributeId") REFERENCES "product_attributes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_b41dfbf95f156aae9fdca612917" FOREIGN KEY ("ordersId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_attributes" ADD CONSTRAINT "FK_5b71e4ee5c131f84708b9a0f358" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "variant_details" ADD CONSTRAINT "FK_d4f431402ec804d3834a83369f8" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_offers" ADD CONSTRAINT "FK_9cbedcf16abd5715a1b84686531" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product-images" ADD CONSTRAINT "FK_e1706dd0f5669c2054d9442cace" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_782da5e50e94b763eb63225d69d" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ff56834e735fa78a15d0cf21926" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shows" ADD CONSTRAINT "FK_48e2dfddd5b05707c16bbb64cc5" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shows" ADD CONSTRAINT "FK_64a44f8b120c55d3bb97e377bb0" FOREIGN KEY ("lpId") REFERENCES "landing-pages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shows" ADD CONSTRAINT "FK_5569d4418eb140b5c1703e11a96" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "landing-pages" ADD CONSTRAINT "FK_1d0527ff07a541b4c6b8f478e39" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_8624dad595ae567818ad9983b33" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_0f82354e5b05fd87884eff3a7b5" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_c20605c444e250f5b4f0df3c456" FOREIGN KEY ("variantDetailId") REFERENCES "variant_details"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_64a6ac9b5af68bf37e781eebb37" FOREIGN KEY ("offerId") REFERENCES "product_offers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_1e9411ff976485dd9fc47209c91" FOREIGN KEY ("customerWilayaId") REFERENCES "wilayas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_4183c202764183e8b578a02efa2" FOREIGN KEY ("customerCommuneId") REFERENCES "communes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_22993947772099159fe52c79212" FOREIGN KEY ("lpId") REFERENCES "landing-pages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "communes" ADD CONSTRAINT "FK_449f99e587e8e13681b6655263d" FOREIGN KEY ("wilayaId") REFERENCES "wilayas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shippings" ADD CONSTRAINT "FK_bf0196789389b7f3bc043b9b053" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shippings" ADD CONSTRAINT "FK_3e245617a649445c21223d91227" FOREIGN KEY ("wilayaId") REFERENCES "wilayas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_6bb58f2b6e30cb51a6504599f41" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "plans" ADD CONSTRAINT "FK_f998a690a409e6e90f956c7030d" FOREIGN KEY ("featuresId") REFERENCES "plan_features"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_7536cba909dd7584a4640cad7d5" FOREIGN KEY ("planId") REFERENCES "plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_shipping_settings" ADD CONSTRAINT "FK_53ba2de9da70861cda5fcba3b7c" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "store_shipping_settings" DROP CONSTRAINT "FK_53ba2de9da70861cda5fcba3b7c"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_7536cba909dd7584a4640cad7d5"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP CONSTRAINT "FK_f998a690a409e6e90f956c7030d"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_6bb58f2b6e30cb51a6504599f41"`);
        await queryRunner.query(`ALTER TABLE "shippings" DROP CONSTRAINT "FK_3e245617a649445c21223d91227"`);
        await queryRunner.query(`ALTER TABLE "shippings" DROP CONSTRAINT "FK_bf0196789389b7f3bc043b9b053"`);
        await queryRunner.query(`ALTER TABLE "communes" DROP CONSTRAINT "FK_449f99e587e8e13681b6655263d"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_22993947772099159fe52c79212"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_4183c202764183e8b578a02efa2"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_1e9411ff976485dd9fc47209c91"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_64a6ac9b5af68bf37e781eebb37"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_c20605c444e250f5b4f0df3c456"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_0f82354e5b05fd87884eff3a7b5"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_8624dad595ae567818ad9983b33"`);
        await queryRunner.query(`ALTER TABLE "landing-pages" DROP CONSTRAINT "FK_1d0527ff07a541b4c6b8f478e39"`);
        await queryRunner.query(`ALTER TABLE "shows" DROP CONSTRAINT "FK_5569d4418eb140b5c1703e11a96"`);
        await queryRunner.query(`ALTER TABLE "shows" DROP CONSTRAINT "FK_64a44f8b120c55d3bb97e377bb0"`);
        await queryRunner.query(`ALTER TABLE "shows" DROP CONSTRAINT "FK_48e2dfddd5b05707c16bbb64cc5"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ff56834e735fa78a15d0cf21926"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_782da5e50e94b763eb63225d69d"`);
        await queryRunner.query(`ALTER TABLE "product-images" DROP CONSTRAINT "FK_e1706dd0f5669c2054d9442cace"`);
        await queryRunner.query(`ALTER TABLE "product_offers" DROP CONSTRAINT "FK_9cbedcf16abd5715a1b84686531"`);
        await queryRunner.query(`ALTER TABLE "variant_details" DROP CONSTRAINT "FK_d4f431402ec804d3834a83369f8"`);
        await queryRunner.query(`ALTER TABLE "product_attributes" DROP CONSTRAINT "FK_5b71e4ee5c131f84708b9a0f358"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_b41dfbf95f156aae9fdca612917"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_f31b2790936aab19a62e4c0828a"`);
        await queryRunner.query(`ALTER TABLE "stores" DROP CONSTRAINT "FK_ba690aca3652a749546e8df22dc"`);
        await queryRunner.query(`ALTER TABLE "stores" DROP CONSTRAINT "FK_a3f1c17291011aa7bc7620df482"`);
        await queryRunner.query(`ALTER TABLE "stores" DROP CONSTRAINT "FK_f36d697e265ed99b80cae6984c9"`);
        await queryRunner.query(`ALTER TABLE "theme_user" DROP CONSTRAINT "FK_93dccfcad09b5fb21e1e96e609e"`);
        await queryRunner.query(`ALTER TABLE "theme" DROP CONSTRAINT "FK_9eb2f43ba51035528ddb77e8982"`);
        await queryRunner.query(`ALTER TABLE "store_pixels" DROP CONSTRAINT "FK_d672c71dc8dd7bb3670942830e3"`);
        await queryRunner.query(`ALTER TABLE "store_hero_sections" DROP CONSTRAINT "FK_d2d33adeaf7b8f987e4d8e274fb"`);
        await queryRunner.query(`ALTER TABLE "store_contacts" DROP CONSTRAINT "FK_1627fed74b48fa87174a0e66620"`);
        await queryRunner.query(`ALTER TABLE "store_topbars" DROP CONSTRAINT "FK_6549c1d9ad39cd06be3d213e3b5"`);
        await queryRunner.query(`ALTER TABLE "store_designs" DROP CONSTRAINT "FK_017647ff1af091772e3bdf80ba2"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_fa6ba3528de12e174b163c09fdd"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa"`);
        await queryRunner.query(`ALTER TABLE "images" DROP CONSTRAINT "FK_96514329909c945f10974aff5f8"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_2ecdb33f23e9a6fc392025c0b97"`);
        await queryRunner.query(`DROP TABLE "admin"`);
        await queryRunner.query(`DROP TABLE "store_shipping_settings"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "users_role_enum"`);
        await queryRunner.query(`DROP TYPE "users_provider_enum"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "subscriptions_interval_enum"`);
        await queryRunner.query(`DROP TYPE "subscriptions_status_enum"`);
        await queryRunner.query(`DROP TABLE "plans"`);
        await queryRunner.query(`DROP TABLE "plan_features"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TYPE "transactions_type_enum"`);
        await queryRunner.query(`DROP TYPE "transactions_action_enum"`);
        await queryRunner.query(`DROP TABLE "shippings"`);
        await queryRunner.query(`DROP TABLE "wilayas"`);
        await queryRunner.query(`DROP TABLE "communes"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "orders_status_enum"`);
        await queryRunner.query(`DROP TYPE "orders_typeship_enum"`);
        await queryRunner.query(`DROP TABLE "landing-pages"`);
        await queryRunner.query(`DROP TABLE "shows"`);
        await queryRunner.query(`DROP INDEX "IDX_56b0fbad8cf5578cb7536e9839"`);
        await queryRunner.query(`DROP INDEX "IDX_bb4c06bfc223160d712f7ea457"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "product-images"`);
        await queryRunner.query(`DROP TABLE "product_offers"`);
        await queryRunner.query(`DROP TABLE "variant_details"`);
        await queryRunner.query(`DROP TABLE "product_attributes"`);
        await queryRunner.query(`DROP TABLE "product_variants"`);
        await queryRunner.query(`DROP TABLE "stores"`);
        await queryRunner.query(`DROP TABLE "theme_user"`);
        await queryRunner.query(`DROP TABLE "theme"`);
        await queryRunner.query(`DROP TABLE "theme_type"`);
        await queryRunner.query(`DROP TABLE "store_pixels"`);
        await queryRunner.query(`DROP TYPE "store_pixels_type_enum"`);
        await queryRunner.query(`DROP TABLE "store_hero_sections"`);
        await queryRunner.query(`DROP TABLE "store_contacts"`);
        await queryRunner.query(`DROP TABLE "store_topbars"`);
        await queryRunner.query(`DROP TABLE "store_designs"`);
        await queryRunner.query(`DROP TABLE "niches"`);
        await queryRunner.query(`DROP INDEX "IDX_b46b2ebf13699bb37073964de2"`);
        await queryRunner.query(`DROP INDEX "IDX_a8a585f8f8acb7dba7112b9ee6"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "images"`);
        await queryRunner.query(`DROP TABLE "wallets"`);
    }

}
